# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # or whatever version you need

      # Install Python dependencies
    - name: Install Python packages
      run: |
        set -e
        python -m pip install --upgrade pip
        pip install numpy
        pip install pandas
        pip install torch
        pip install ase
        pip install torchani
        pip install torch
    
    - run: npm ci
    - run: python Backend.py
    - run: cat public/data.json
    - run: npm run build 
    - run: cat build/data.json
    - run: npm test

    - name: Deploy with gh-pages
      run: |
       git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
       npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>" 
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

  